openapi: 3.2.0
info:
  title: Reference Eng Sequences API
  version: '2.0'
  summary: API
  description: "Vessel's APIs requires an access token to be used together with your Vessel API token. Ensure the following headers are provided when making API calls:\n\nKey | Value | Description\n---------|----------|----------\n vessel-api-token | `<VESSEL_API_TOKEN>` | The API token provided by us\n \nAdditionally, in the query or body parameters of each request depending on whether it is a GET or POST, make sure to include the `accessToken` for the connection you want to access."
servers:
- url: https://api.vessel.land
security:
- VesselAPIToken: []
tags:
- name: engSequences
paths:
  /engagement/sequences:
    parameters: []
    get:
      summary: Get All Sequences
      tags:
      - engSequences
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                title: responseBody
                type: object
                properties:
                  sequences:
                    type: array
                    items:
                      $ref: '#/components/schemas/EngSequence'
                  nextPageCursor:
                    type: string
              examples:
                example-1:
                  value:
                    sequences:
                    - id: 2322707bbc41577d9806400e2daa25de
                      isEnabled: true
                      name: Reaching out about My Company
                      tags:
                      - cold
                      numSteps: 1
                      scheduledCount: 0
                      openedCount: 0
                      optedOutCount: 0
                      repliedCount: 0
                      clickedCount: 0
                    nextPageCursor: d9806400e2daa25de2322707bbc41577
      operationId: get-all-engagement-sequences
      parameters:
      - $ref: '#/components/parameters/accessToken'
      - $ref: '#/components/parameters/cursor'
      - $ref: '#/components/parameters/limit'
      - $ref: '#/components/parameters/allFields'
      description: Retrieve all Sequences
      security:
      - VesselAPIToken: []
  /engagement/sequence/start:
    parameters: []
    post:
      summary: Start Sequence
      tags:
      - engSequences
      operationId: post-start-engagement-sequence
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                title: responseBody
                type: object
                properties:
                  id:
                    type: string
              examples:
                example-1:
                  value:
                    id: '0'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                accessToken:
                  type: string
                fields:
                  $ref: '#/components/schemas/EngSequenceStart'
              required:
              - id
              - accessToken
              - fields
            examples:
              example-1:
                value:
                  id: 939f3f91233b4b0e8f0f2a0f2a0f2a0f
                  accessToken: string
                  fields:
                    contactId: 233b4b8f0f2910ea0f2a0f2a0f939f3f
                    mailboxId: 8f0f2a0f2a0f2a0f939f3f91233b4b0e
      description: Complete an action to move a prospect to the next step of a sequence.
  /engagement/sequence:
    parameters: []
    post:
      summary: Create Sequence
      tags:
      - engSequences
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                title: responseBody
                type: object
                properties:
                  id:
                    type: string
              examples:
                example-1:
                  value:
                    id: 2322707bbc41577d9806400e2daa25de
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                accessToken:
                  type: string
                sequence:
                  $ref: '#/components/schemas/EngSequenceCreate'
              required:
              - accessToken
              - sequence
            examples:
              example-1:
                value:
                  accessToken: string
                  sequence:
                    name: Email Sequence
                    shareType: team
                    additional: {}
      operationId: post-engagement-sequences
      description: Create an empty Sequence. To add steps to the sequence, use the /engagement/sequence/step endpoint.
      security:
      - VesselAPIToken: []
  /engagement/sequence/step:
    parameters: []
    post:
      summary: Create Sequence Step
      tags:
      - engSequences
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                title: responseBody
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                accessToken:
                  type: string
                steps:
                  type: array
                  items:
                    $ref: '#/components/schemas/EngSequenceStepCreate'
              required:
              - accessToken
              - steps
            examples:
              example-1:
                value:
                  accessToken: string
                  steps:
                  - name: Step 1 (Automated Email)
                    type: auto_email
                    daysAfter: 2
                    settings:
                      templateName: Email Template
                      isReply: false
                      subject: Hello from Dunder!
                      body: Hi {{first_name}}! I'm reaching out to ask you about your paper needs.
                    additional: {}
      operationId: post-engagement-sequences-steps
      description: Create one or more steps in a sequence.
      security:
      - VesselAPIToken: []
components:
  schemas:
    EngSequenceCreate:
      title: Create Sequence
      type: object
      description: null
      examples:
      - name: Email Sequence
        shareType: team
        additional: {}
      properties:
        name:
          type: string
        shareType:
          type: string
          enum:
          - team
          - private
          description: '''team'' will share the sequence with all users in the team. ''private'' will only share the sequence with the user that created it.'
        additional:
          type: object
          description: Create any property in the downstream Engagement Platform, such as a custom property.
      required:
      - name
      - shareType
    EngSequence:
      title: Sequence
      type: object
      description: Properties that a sequence can be created with
      examples:
      - id: 2322707bbc41577d9806400e2daa25de
        isEnabled: true
        name: Reaching out about My Company
        tags:
        - cold
        numSteps: 1
        scheduledCount: 0
        openedCount: 0
        optedOutCount: 0
        repliedCount: 0
        clickedCount: 0
      properties:
        id:
          type: string
        isEnabled:
          type: boolean
        name:
          type: string
        tags:
          type: array
          items:
            type: string
        numSteps:
          type: number
          description: Not supported in Salesloft.
        scheduledCount:
          type: number
        openedCount:
          type: number
          description: Not supported in Salesloft.
        optedOutCount:
          type: number
          description: Not supported in Salesloft.
        repliedCount:
          type: number
          description: Not supported in Salesloft.
        clickedCount:
          type: number
          description: Not supported in Salesloft.
        createdTime:
          type: string
          description: The timestamp that the user was created
        modifiedTime:
          type: string
          description: Not supported by Apollo. The timestamp the user was last modified
    EngSequenceStepSettingsCreate:
      title: Create Sequence Step Settings
      type: object
      properties:
        templateName:
          type: string
          description: The name for this template
        isReply:
          type: boolean
          description: Whether or not this email is a reply to the previous step's email
        subject:
          type: string
          description: The subject line for this email
        body:
          type: string
          description: The body of the email
    EngSequenceStepCreate:
      title: Create Sequence Steps
      type: object
      description: properties that a sequence step can be created with
      examples:
      - name: Step 1 (Automated Email)
        type: auto_email
        daysAfter: 2
        settings:
          templateName: Email Template
          isReply: false
          subject: Hello from Dunder!
          body: Hi {{first_name}}! I'm reaching out to ask you about your paper needs.
        additional: {}
      properties:
        name:
          type: string
        type:
          type: string
          enum:
          - auto_email
          - manual_email
        daysAfter:
          type: number
          description: The number of days after the previous step that this step should be sent.
        settings:
          $ref: '#/components/schemas/EngSequenceStepSettingsCreate'
        additional:
          type: object
          description: Use the additional property to make updates to properties in the Engagement Platform not current supported by Vessel.
      required:
      - name
      - type
      - settings
      - shareType
    EngSequenceStart:
      title: SequenceStart
      type: object
      description: Start a sequence
      examples:
      - contactId: 233b4b8f0f2910ea0f2a0f2a0f939f3f
        mailboxId: 8f0f2a0f2a0f2a0f939f3f91233b4b0e
      properties:
        contactId:
          type: string
        mailboxId:
          type: string
  parameters:
    cursor:
      name: cursor
      in: query
      description: The cursor to use for pagination
      schema:
        type: string
    accessToken:
      name: accessToken
      in: query
      description: The token for the customer's account. This was generated when they connected their account.
      required: true
      schema:
        type: string
    allFields:
      name: allFields
      in: query
      description: Returns all fields including non-unifiable and custom fields under the "additional" property in the response
      schema:
        type: boolean
    limit:
      name: limit
      in: query
      description: The number of records to return per page.
      schema:
        type: number
  securitySchemes:
    VesselAPIToken:
      name: vessel-api-token
      type: apiKey
      in: header
x-speakeasy-name-override:
- operationId: post-*
  methodNameOverride: create
- operationId: put-*
  methodNameOverride: update
- operationId: delete-*
  methodNameOverride: delete
- operationId: get-one-*
  methodNameOverride: find
- operationId: get-all-*
  methodNameOverride: list
- operationId: get-details-*
  methodNameOverride: details
- operationId: get-batch-*
  methodNameOverride: batch
- operationId: search-*
  methodNameOverride: search
