openapi: 3.2.0
info:
  title: CRM API Reference Leads API
  version: '2.0'
  summary: API
servers:
- url: https://api.vessel.dev
security:
- VesselAPIToken: []
tags:
- name: leads
paths:
  /crm/leads:
    get:
      summary: Get All Leads
      tags:
      - leads
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                title: responseBody
                type: object
                properties:
                  leads:
                    type: array
                    items:
                      $ref: '#/components/schemas/Lead'
                  nextPageCursor:
                    type: string
              examples:
                example-1:
                  value:
                    leads:
                    - id: v.lead.d08f345ace24509e911a0ea8e3d2203c
                      nativeId: '23'
                      firstName: Tom
                      lastName: Smith
                      jobTitle: Director of Operations
                      email: tom@bluecross.com
                      account: Blue Cross
                      phone: '1234445555'
                      mobilePhone: '2338889999'
                      createdTime: '2019-08-24T14:15:22Z'
                      modifiedTime: '2019-08-24T14:15:22Z'
                      associations:
                        contactIds:
                        - v.contact.e5f32d4fd2115220bd20a2ccf81210ec
                        accountIds:
                        - v.account.0dcb45e051315a6ea63b0f16e73689d9
                        noteIds:
                        - v.note.006b4db16b6b50c981a174b02753c390
                        taskIds:
                        - v.task.2322707bbc41577d9806400e2daa25de
                        eventIds:
                        - v.event.0000d2e83d6c5d52a61f2fb860666477
                        eventAttendeeIds:
                        - v.attendee.f63c1bd7215f5150b332d31d9509752f
                        emailIds:
                        - v.email.3ab3a9562af957228c1019127e3c81e1
                        callIds:
                        - v.call.1222707bbc415ee4806400e2daa25ffa
                      additional: {}
                    nextPageCursor: string
      operationId: get-all-crm-leads
      description: 'Retrieve all leads.

        *CRM Caveats*:

        - Pipedrive: Only `jobTitle` is returned when querying for all leads'
      parameters:
      - schema:
          type: string
        in: query
        name: accessToken
        description: The token for the customer's CRM account. This was generated when they connected their account.
        required: true
      - schema:
          type: string
        in: query
        name: cursor
      - schema:
          type: number
        in: query
        name: limit
        description: The number of records to return per page.
      - schema:
          type: boolean
        in: query
        name: allFields
        description: Returns all fields including non-unifiable and custom fields under the "additional" property in the response
  /crm/leads/search:
    post:
      summary: Search Leads
      tags:
      - leads
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                filters:
                  type: object
                  properties:
                    id:
                      $ref: '#/components/schemas/StringFilter'
                    nativeId:
                      $ref: '#/components/schemas/StringFilter'
                    lastName:
                      $ref: '#/components/schemas/StringFilter'
                    firstName:
                      $ref: '#/components/schemas/StringFilter'
                    jobTitle:
                      $ref: '#/components/schemas/StringFilter'
                    email:
                      $ref: '#/components/schemas/StringFilter'
                    account:
                      $ref: '#/components/schemas/StringFilter'
                    phone:
                      $ref: '#/components/schemas/StringFilter'
                    mobilePhone:
                      $ref: '#/components/schemas/StringFilter'
                    createdTime:
                      $ref: '#/components/schemas/DateFilter'
                    modifiedTime:
                      $ref: '#/components/schemas/DateFilter'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  leads:
                    type: array
                    items:
                      $ref: '#/components/schemas/Lead'
                  nextPageCursor:
                    type: string
                title: responseBody
              examples:
                example-1:
                  value:
                    leads:
                    - id: v.lead.d08f345ace24509e911a0ea8e3d2203c
                      nativeId: '23'
                      firstName: Tom
                      lastName: Smith
                      jobTitle: Director of Operations
                      email: tom@bluecross.com
                      account: Blue Cross
                      phone: '1234445555'
                      mobilePhone: '2338889999'
                      createdTime: '2019-08-24T14:15:22Z'
                      modifiedTime: '2019-08-24T14:15:22Z'
                      associations:
                        contactIds:
                        - v.contact.e5f32d4fd2115220bd20a2ccf81210ec
                        accountIds:
                        - v.account.0dcb45e051315a6ea63b0f16e73689d9
                        noteIds:
                        - v.note.006b4db16b6b50c981a174b02753c390
                        taskIds:
                        - v.task.2322707bbc41577d9806400e2daa25de
                        eventIds:
                        - v.event.0000d2e83d6c5d52a61f2fb860666477
                        eventAttendeeIds:
                        - v.attendee.f63c1bd7215f5150b332d31d9509752f
                        emailIds:
                        - v.email.3ab3a9562af957228c1019127e3c81e1
                        callIds:
                        - v.call.1222707bbc415ee4806400e2daa25ffa
                      additional: {}
                    nextPageCursor: string
      operationId: search-crm-leads
      description: Search all Leads using filters
      parameters:
      - $ref: '#/components/parameters/accessToken'
      - $ref: '#/components/parameters/cursor'
      - $ref: '#/components/parameters/limit'
      - $ref: '#/components/parameters/allFields'
  /crm/lead:
    get:
      summary: Get Lead
      tags:
      - leads
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                title: responseBody
                type: object
                properties:
                  lead:
                    $ref: '#/components/schemas/Lead'
              examples:
                example-1:
                  value:
                    lead:
                      id: v.lead.d08f345ace24509e911a0ea8e3d2203c
                      nativeId: '23'
                      firstName: Tom
                      lastName: Smith
                      jobTitle: Director of Operations
                      email: tom@bluecross.com
                      account: Blue Cross
                      phone: '1234445555'
                      mobilePhone: '2338889999'
                      createdTime: '2019-08-24T14:15:22Z'
                      modifiedTime: '2019-08-24T14:15:22Z'
                      associations:
                        contactIds:
                        - v.contact.e5f32d4fd2115220bd20a2ccf81210ec
                        accountIds:
                        - v.account.0dcb45e051315a6ea63b0f16e73689d9
                        noteIds:
                        - v.note.006b4db16b6b50c981a174b02753c390
                        taskIds:
                        - v.task.2322707bbc41577d9806400e2daa25de
                        eventIds:
                        - v.event.0000d2e83d6c5d52a61f2fb860666477
                        eventAttendeeIds:
                        - v.attendee.f63c1bd7215f5150b332d31d9509752f
                        emailIds:
                        - v.email.3ab3a9562af957228c1019127e3c81e1
                        callIds:
                        - v.call.1222707bbc415ee4806400e2daa25ffa
                      additional: {}
      operationId: get-one-crm-lead
      description: Retrieve a single Lead by Id
      parameters:
      - schema:
          type: string
        in: query
        name: accessToken
        description: The token for the customer's CRM account. This was generated when they connected their account.
        required: true
      - schema:
          type: string
        in: query
        name: id
        required: true
      - schema:
          type: boolean
        in: query
        name: allFields
        description: Returns all fields including non-unifiable and custom fields under the "additional" property in the response
    post:
      summary: Create Lead
      tags:
      - leads
      operationId: post-crm-lead
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                title: responseBody
                description: ''
                type: object
                x-examples:
                  example-1:
                    id: '0'
                properties:
                  id:
                    type: string
                required:
                - id
              examples:
                example-1:
                  value:
                    id: string
      description: Create a new Lead
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                accessToken:
                  type: string
                lead:
                  $ref: '#/components/schemas/LeadCreate'
              required:
              - accessToken
              - lead
            examples:
              example-1:
                value:
                  accessToken: string
                  lead:
                    firstName: Tom
                    lastName: Smith
                    jobTitle: Director of Operations
                    email: tom@bluecross.com
                    account: Blue Cross
                    phone: '1234445555'
                    mobilePhone: '2338889999'
    patch:
      summary: Update Lead
      tags:
      - leads
      operationId: put-crm-lead
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                title: responseBody
                description: ''
                type: object
                x-examples:
                  example-1:
                    id: '0'
                properties:
                  id:
                    type: string
                required:
                - id
              examples:
                example-1:
                  value:
                    id: '0'
      description: Update an existing Lead by Id
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                accessToken:
                  type: string
                id:
                  type: string
                lead:
                  $ref: '#/components/schemas/LeadUpdate'
              required:
              - accessToken
              - id
              - lead
            examples:
              example-1:
                value:
                  accessToken: string
                  lead:
                    firstName: Tom
                    lastName: Smith
                    jobTitle: Director of Operations
                    email: tom@bluecross.com
                    account: Blue Cross
                    phone: '1234445555'
                    mobilePhone: '2338889999'
  /crm/lead/details:
    get:
      summary: Get Lead Details
      tags:
      - leads
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                title: responseBody
                type: object
                properties:
                  fields:
                    type: array
                    items:
                      $ref: '#/components/schemas/Field'
                  nextPageCursor:
                    type: string
              examples:
                example-1:
                  value:
                    fields:
                    - key: firstName
                      name: First Name
                      type: string
                      options: null
                      isArray: false
                      custom: false
                      universal: true
                      required: false
                      creatable: true
                      updatable: true
                    nextPageCursor: string
      operationId: get-details-crm-lead
      description: 'Get details about all leads.

        Details include the type, possible values, and other meta data about the fields.'
      parameters:
      - schema:
          type: string
        in: query
        name: accessToken
        description: The token for the customer's CRM account. This was generated when they connected their account.
        required: true
      - schema:
          type: string
        in: query
        name: cursor
      - schema:
          type: boolean
        in: query
        name: allFields
        description: Returns details about native fields.
  /crm/lead/batch:
    parameters: []
    get:
      summary: Get Batch Leads
      tags:
      - leads
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                title: responseBody
                type: object
                properties:
                  leads:
                    type: array
                    items:
                      $ref: '#/components/schemas/Lead'
                  invalidIds:
                    $ref: '#/components/schemas/InvalidIds'
              examples:
                example-1:
                  value:
                    leads:
                    - id: v.lead.d08f345ace24509e911a0ea8e3d2203c
                      nativeId: '23'
                      firstName: Tom
                      lastName: Smith
                      jobTitle: Director of Operations
                      email: tom@bluecross.com
                      account: Blue Cross
                      phone: '1234445555'
                      mobilePhone: '2338889999'
                      createdTime: '2019-08-24T14:15:22Z'
                      modifiedTime: '2019-08-24T14:15:22Z'
                      associations:
                        contactIds:
                        - v.contact.e5f32d4fd2115220bd20a2ccf81210ec
                        accountIds:
                        - v.account.0dcb45e051315a6ea63b0f16e73689d9
                        noteIds:
                        - v.note.006b4db16b6b50c981a174b02753c390
                        taskIds:
                        - v.task.2322707bbc41577d9806400e2daa25de
                        eventIds:
                        - v.event.0000d2e83d6c5d52a61f2fb860666477
                        eventAttendeeIds:
                        - v.attendee.f63c1bd7215f5150b332d31d9509752f
                        emailIds:
                        - v.email.3ab3a9562af957228c1019127e3c81e1
                        callIds:
                        - v.call.1222707bbc415ee4806400e2daa25ffa
                      additional: {}
      operationId: get-batch-crm-lead
      parameters:
      - schema:
          type: string
        in: query
        name: accessToken
        required: true
        description: The token for the customer's CRM account. This was generated when they connected their account.
      - schema:
          type: string
        in: query
        name: ids
        description: Comma separated list of Lead Id's.
      - schema:
          type: boolean
        in: query
        name: allFields
        description: Returns all fields including non-unifiable and custom fields under the "additional" property in the response
      description: Retrieve Leads by a set of Id's
components:
  schemas:
    LeadCreate:
      description: ''
      type: object
      x-examples:
        example-1:
          firstName: Tony
          lastName: Stark
          jobTitle: CEO
          email: tony@starkindustries.com
          phones:
          - value: '0001112222'
            type: Home
      examples:
      - firstName: Tom
        lastName: Smith
        jobTitle: Director of Operations
        email: tom@bluecross.com
        account: Blue Cross
        phone: '1234445555'
        mobilePhone: '2338889999'
      title: LeadCreate
      properties:
        firstName:
          type: string
        lastName:
          type: string
        jobTitle:
          type: string
        email:
          type: string
        account:
          type: string
          description: 'Name of the Account associated with this lead. Not supported for Pipedrive. Defaults to `[TODO]: Fill in Company Name` in Salesforce'
        phone:
          type: string
          description: The primary phone number for this lead
        mobilePhone:
          type: string
          description: The primary mobile phone number for this lead. Possibly the same as the phone number.
        additional:
          type: object
          description: Create any property in the downstream CRM, such as a custom or native property. For a list of all properties see /details.
      required:
      - lastName
    DateFilter:
      type: object
      properties:
        equals:
          type: string
        gt:
          type: string
        lt:
          type: string
        lte:
          type: string
        gte:
          type: string
        not:
          type: string
        in:
          type: array
          items:
            type: string
        notIn:
          type: array
          items:
            type: string
    InvalidIds:
      type: array
      items:
        type: string
      description: Ids that didn't return anything. Will be an empty array if all Ids are valid.
    LeadUpdate:
      description: ''
      type: object
      x-examples:
        example-1:
          firstName: string
          lastName: string
          jobTitle: string
          email: string
          phones:
          - value: '0001112222'
            type: Home
          modifiedTime: string
          createdTime: string
      examples:
      - firstName: Tom
        lastName: Smith
        jobTitle: Director of Operations
        email: tom@bluecross.com
        account: Blue Cross
        phone: '1234445555'
        mobilePhone: '2338889999'
      title: LeadUpdate
      properties:
        firstName:
          type: string
          description: Not supported for Pipedrive
        lastName:
          type: string
          description: Not supported for Pipedrive
        jobTitle:
          type: string
        email:
          type: string
          description: Not supported for Pipedrive
        account:
          type: string
          description: Name of the Account associated with this lead. Not supported for Pipedrive
        phone:
          type: string
          description: The primary phone. Not supported for Pipedrive
        mobilePhone:
          type: string
          description: The primary mobile phone number for this lead. Possibly the same as the phone number. Not supported for Pipedrive
        additional:
          type: object
          description: Create any property in the downstream CRM, such as a custom or native property. For a list of all properties see /details.
    Field:
      title: Field
      type: object
      description: '(Alias: property) A field is a key-value pair on a CRM Object that provides information about that object.'
      properties:
        key:
          type: string
          description: 'The key in the CRM object (ex: annualRevenue, numberOfEmployees, etc)'
        name:
          type: string
          description: 'The display name of this field (ex: number of employees, annual revenue, etc)'
        type:
          type: string
          enum:
          - string
          - number
          - datetime
          - date
          - boolean
          - reference
          - phone
          - url
          - id
          - email
          - percent
          - singleselect
          - multiselect
          - address
          - decimal
          - time
          - daterange
          - object
        options:
          type: array
          description: Possible options for this field
          items:
            type: object
            properties:
              key:
                oneOf:
                - type: string
                - type: number
              name:
                type: string
        isArray:
          type: boolean
          description: If this field is an array
        custom:
          type: boolean
          description: If this field is a custom field
        universal:
          type: boolean
          description: If this is a field we've unified across CRMs
        required:
          type: boolean
          description: If this field is required when creating the object
        creatable:
          type: boolean
          description: If this field can be used when creating the object
        updatable:
          type: boolean
          description: If this field can be updated
      required:
      - key
      - name
      - type
      - custom
      - universal
      - required
      - creatable
      - updatable
      examples:
      - key: numberOfEmployees
        name: number of employees
        type: number
        options: null
        isArray: false
        custom: false
        universal: true
        required: false
        creatable: true
        updatable: true
    StringFilter:
      type: object
      properties:
        equals:
          type: string
        contains:
          type: string
        startsWith:
          type: string
        endsWith:
          type: string
        not:
          type: string
        in:
          type: array
          items:
            type: string
        notIn:
          type: array
          items:
            type: string
        mode:
          type: string
          enum:
          - insensitive
    Lead:
      title: Lead
      type: object
      description: 'A Lead represents an individual, or sometimes an organization, that is interested in purchasing your product (i.e., is a potential Deal).

        *CRM Caveats*:

        - HubSpot: we consider contacts with the `leadStatus` set to be leads.'
      examples:
      - id: v.lead.d08f345ace24509e911a0ea8e3d2203c
        nativeId: '23'
        firstName: Tom
        lastName: Smith
        jobTitle: Director of Operations
        email: tom@bluecross.com
        account: Blue Cross
        phone: '1234445555'
        mobilePhone: '2338889999'
        createdTime: '2019-08-24T14:15:22Z'
        modifiedTime: '2019-08-24T14:15:22Z'
        associations:
          contactIds:
          - v.contact.e5f32d4fd2115220bd20a2ccf81210ec
          accountIds:
          - v.account.0dcb45e051315a6ea63b0f16e73689d9
          noteIds:
          - v.note.006b4db16b6b50c981a174b02753c390
          taskIds:
          - v.task.2322707bbc41577d9806400e2daa25de
          eventIds:
          - v.event.0000d2e83d6c5d52a61f2fb860666477
          eventAttendeeIds:
          - v.attendee.f63c1bd7215f5150b332d31d9509752f
          emailIds:
          - v.email.3ab3a9562af957228c1019127e3c81e1
          callIds:
          - v.call.1222707bbc415ee4806400e2daa25ffa
        additional: {}
      properties:
        id:
          type: string
          description: Unique Vessel Id.
        nativeId:
          type: string
          description: Id of the object in the connected CRM.
        firstName:
          type: string
        lastName:
          type: string
        jobTitle:
          type: string
        email:
          type: string
        account:
          type: string
          description: Name of the Account associated with this lead
        phone:
          type: string
          description: The primary phone
        mobilePhone:
          type: string
          description: The primary mobile phone number for this lead. Possibly the same as the phone number
        createdTime:
          type: string
          description: The timestamp that the lead was created
        modifiedTime:
          type: string
          description: The timestamp the lead was last modified
        associations:
          type: object
          required:
          - contactIds
          - accountIds
          - noteIds
          - taskIds
          - eventIds
          - eventAttendeeIds
          - emailIds
          - callIds
          properties:
            contactIds:
              type: array
              items:
                type: string
            accountIds:
              type: array
              items:
                type: string
            noteIds:
              type: array
              items:
                type: string
            taskIds:
              type: array
              items:
                type: string
            eventIds:
              type: array
              items:
                type: string
            eventAttendeeIds:
              type: array
              items:
                type: string
            emailIds:
              type: array
              items:
                type: string
            callIds:
              type: array
              items:
                type: string
        additional:
          type: object
          description: Returned when `allFields` is set in the query params. Includes all data, untransformed, we received from the downstream CRM
      required:
      - id
      - nativeId
      - createdTime
      - modifiedTime
      - associations
  parameters:
    cursor:
      name: cursor
      in: query
      description: The cursor to use for pagination
      schema:
        type: string
    accessToken:
      name: accessToken
      in: query
      description: The token for the customer's account. This was generated when they connected their account.
      required: true
      schema:
        type: string
    allFields:
      name: allFields
      in: query
      description: Returns all fields including non-unifiable and custom fields under the "additional" property in the response
      schema:
        type: boolean
    limit:
      name: limit
      in: query
      description: The number of records to return per page.
      schema:
        type: number
  securitySchemes:
    VesselAPIToken:
      name: vessel-api-token
      type: apiKey
      in: header
