openapi: 3.2.0
info:
  title: CRM API Reference Contacts API
  version: '2.0'
  summary: API
servers:
- url: https://api.vessel.dev
security:
- VesselAPIToken: []
tags:
- name: contacts
paths:
  /crm/contacts:
    parameters: []
    get:
      summary: Get All Contacts
      tags:
      - contacts
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                title: responseBody
                type: object
                properties:
                  contacts:
                    type: array
                    items:
                      $ref: '#/components/schemas/Contact'
                  nextPageCursor:
                    type: string
              examples:
                example-1:
                  value:
                    contacts:
                    - id: v.contact.e5f32d4fd2115220bd20a2ccf81210ec
                      nativeId: '23'
                      email: tom@bluecross.com
                      firstName: Tom
                      lastName: Smith
                      jobTitle: Director of Operations
                      phone: '2101128833'
                      mobilePhone: '2106541111'
                      createdTime: '2019-08-24T14:15:22Z'
                      modifiedTime: '2019-08-24T14:15:22Z'
                      associations:
                        accountIds:
                        - v.account.0dcb45e051315a6ea63b0f16e73689d9
                        dealIds:
                        - v.deal.497fb529e6805351b5dc8057c74a4a52
                        leadIds:
                        - v.lead.d08f345ace24509e911a0ea8e3d2203c
                        noteIds:
                        - v.note.006b4db16b6b50c981a174b02753c390
                        taskIds:
                        - v.task.2322707bbc41577d9806400e2daa25de
                        eventIds:
                        - v.event.0000d2e83d6c5d52a61f2fb860666477
                        eventAttendeeIds:
                        - v.attendee.f63c1bd7215f5150b332d31d9509752f
                        emailIds:
                        - v.email.3ab3a9562af957228c1019127e3c81e1
                        ownerUserId: v.user.56f653659ea9524b9e0fb0ba67e6f8a0
                      additional: {}
                    nextPageCursor: string
      operationId: get-all-crm-contacts
      parameters:
      - schema:
          type: string
        in: query
        name: accessToken
        description: The token for the customer's CRM account. This was generated when they connected their account.
        required: true
      - schema:
          type: string
        in: query
        name: cursor
      - schema:
          type: number
        in: query
        name: limit
        description: The number of records to return per page.
      - schema:
          type: boolean
        in: query
        name: allFields
        description: Returns all fields including non-unifiable and custom fields under the "additional" property in the response
      description: Retrieve all Contacts
  /crm/contacts/search:
    post:
      summary: Search Contacts
      tags:
      - contacts
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                filters:
                  type: object
                  properties:
                    id:
                      $ref: '#/components/schemas/StringFilter'
                    nativeId:
                      $ref: '#/components/schemas/StringFilter'
                    firstName:
                      $ref: '#/components/schemas/StringFilter'
                    lastName:
                      $ref: '#/components/schemas/StringFilter'
                    jobTitle:
                      $ref: '#/components/schemas/StringFilter'
                    email:
                      $ref: '#/components/schemas/StringFilter'
                    phone:
                      $ref: '#/components/schemas/StringFilter'
                    mobilePhone:
                      $ref: '#/components/schemas/StringFilter'
                    createdTime:
                      $ref: '#/components/schemas/DateFilter'
                    modifiedTime:
                      $ref: '#/components/schemas/DateFilter'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  contacts:
                    type: array
                    items:
                      $ref: '#/components/schemas/Contact'
                  nextPageCursor:
                    type: string
                title: responseBody
              examples:
                example-1:
                  value:
                    contacts:
                    - id: v.contact.e5f32d4fd2115220bd20a2ccf81210ec
                      nativeId: '23'
                      email: tom@bluecross.com
                      firstName: Tom
                      lastName: Smith
                      jobTitle: Director of Operations
                      phone: '2101128833'
                      mobilePhone: '2106541111'
                      createdTime: '2019-08-24T14:15:22Z'
                      modifiedTime: '2019-08-24T14:15:22Z'
                      associations:
                        accountIds:
                        - v.account.0dcb45e051315a6ea63b0f16e73689d9
                        dealIds:
                        - v.deal.497fb529e6805351b5dc8057c74a4a52
                        leadIds:
                        - v.lead.d08f345ace24509e911a0ea8e3d2203c
                        noteIds:
                        - v.note.006b4db16b6b50c981a174b02753c390
                        taskIds:
                        - v.task.2322707bbc41577d9806400e2daa25de
                        eventIds:
                        - v.event.0000d2e83d6c5d52a61f2fb860666477
                        eventAttendeeIds:
                        - v.attendee.f63c1bd7215f5150b332d31d9509752f
                        emailIds:
                        - v.email.3ab3a9562af957228c1019127e3c81e1
                        callIds:
                        - v.call.1222707bbc415ee4806400e2daa25ffa
                        ownerUserId: v.user.56f653659ea9524b9e0fb0ba67e6f8a0
                      additional: {}
                    nextPageCursor: string
      operationId: search-crm-contacts
      description: Search all Contacts using filters
      parameters:
      - $ref: '#/components/parameters/accessToken'
      - $ref: '#/components/parameters/cursor'
      - $ref: '#/components/parameters/limit'
      - $ref: '#/components/parameters/allFields'
  /crm/contact:
    parameters: []
    get:
      summary: Get Contact
      tags:
      - contacts
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                title: responseBody
                type: object
                properties:
                  contact:
                    $ref: '#/components/schemas/Contact'
              examples:
                example-1:
                  value:
                    contact:
                      id: v.contact.e5f32d4fd2115220bd20a2ccf81210ec
                      nativeId: '23'
                      email: tom@bluecross.com
                      firstName: Tom
                      lastName: Smith
                      jobTitle: Director of Operations
                      phone: '2101128833'
                      mobilePhone: '2106541111'
                      createdTime: '2019-08-24T14:15:22Z'
                      modifiedTime: '2019-08-24T14:15:22Z'
                      associations:
                        accountIds:
                        - v.account.0dcb45e051315a6ea63b0f16e73689d9
                        dealIds:
                        - v.deal.497fb529e6805351b5dc8057c74a4a52
                        leadIds:
                        - v.lead.d08f345ace24509e911a0ea8e3d2203c
                        noteIds:
                        - v.note.006b4db16b6b50c981a174b02753c390
                        taskIds:
                        - v.task.2322707bbc41577d9806400e2daa25de
                        eventIds:
                        - v.event.0000d2e83d6c5d52a61f2fb860666477
                        eventAttendeeIds:
                        - v.attendee.f63c1bd7215f5150b332d31d9509752f
                        emailIds:
                        - v.email.3ab3a9562af957228c1019127e3c81e1
                        callIds:
                        - v.call.1222707bbc415ee4806400e2daa25ffa
                        ownerUserId: v.user.56f653659ea9524b9e0fb0ba67e6f8a0
                      additional: {}
      operationId: get-one-crm-contact
      parameters:
      - schema:
          type: string
        in: query
        name: accessToken
        description: The token for the customer's CRM account. This was generated when they connected their account.
        required: true
      - schema:
          type: string
        in: query
        name: id
        description: The id of the contact to get
      - schema:
          type: boolean
        in: query
        name: allFields
        description: Returns all fields including non-unifiable and custom fields under the "additional" property in the response
      description: Retrieve a Contact by either Id or email. When both email and Id are included, Id will take priority.
    post:
      summary: Create Contact
      tags:
      - contacts
      operationId: post-crm-contact
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                title: responseBody
                type: object
                properties:
                  id:
                    type: string
              examples:
                example-1:
                  value:
                    id: '0'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                accessToken:
                  type: string
                contact:
                  $ref: '#/components/schemas/ContactCreate'
              required:
              - accessToken
              - contact
            examples:
              example-1:
                value:
                  accessToken: string
                  contact:
                    email: tom@bluecross.com
                    firstName: Tom
                    lastName: Smith
                    jobTitle: Director of Operations
                    phone: '2101128833'
                    mobilePhone: '2106541111'
      description: Create a new contact.
    patch:
      summary: Update Contact
      tags:
      - contacts
      operationId: put-crm-contact
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                title: responseBody
                description: ''
                type: object
                x-examples:
                  example-1:
                    id: '0'
                properties:
                  id:
                    type: string
                required:
                - id
              examples:
                example-1:
                  value:
                    id: '0'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                accessToken:
                  type: string
                id:
                  type: string
                contact:
                  $ref: '#/components/schemas/ContactUpdate'
              required:
              - accessToken
              - id
              - contact
            examples:
              example-1:
                value:
                  accessToken: string
                  id: string
                  contact:
                    email: tom@bluecross.com
                    firstName: Tom
                    lastName: Smith
                    jobTitle: Director of Operations
                    phone: '2101128833'
                    mobilePhone: '2106541111'
          application/xml:
            schema:
              type: object
              properties: {}
        description: ''
      description: Update an existing Contact.
  /crm/contact/details:
    get:
      summary: Get Contact Details
      tags:
      - contacts
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                title: responseBody
                type: object
                properties:
                  fields:
                    type: array
                    items:
                      $ref: '#/components/schemas/Field'
                  nextPageCursor:
                    type: string
              examples:
                example-1:
                  value:
                    fields:
                    - key: firstName
                      name: First name
                      type: string
                      options: null
                      isArray: false
                      custom: false
                      universal: true
                      required: false
                      creatable: true
                      updatable: true
                    nextPageCursor: string
      operationId: get-details-crm-contact
      description: 'Get details about all contacts.

        Details include the type, possible values, and other meta data about the fields.'
      parameters:
      - schema:
          type: string
        in: query
        name: accessToken
        description: The token for the customer's CRM account. This was generated when they connected their account.
        required: true
      - schema:
          type: string
        in: query
        name: cursor
      - schema:
          type: boolean
        in: query
        name: allFields
        description: Returns details about native fields.
  /crm/contact/batch:
    parameters: []
    get:
      summary: Get Batch Contacts
      tags:
      - contacts
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                title: responseBody
                type: object
                properties:
                  contacts:
                    type: array
                    items:
                      $ref: '#/components/schemas/Contact'
                  invalidIds:
                    $ref: '#/components/schemas/InvalidIds'
              examples:
                example-1:
                  value:
                    contacts:
                    - id: v.contact.e5f32d4fd2115220bd20a2ccf81210ec
                      nativeId: '23'
                      email: tom@bluecross.com
                      firstName: Tom
                      lastName: Smith
                      jobTitle: Director of Operations
                      phone: '2101128833'
                      mobilePhone: '2106541111'
                      createdTime: '2019-08-24T14:15:22Z'
                      modifiedTime: '2019-08-24T14:15:22Z'
                      associations:
                        accountIds:
                        - v.account.0dcb45e051315a6ea63b0f16e73689d9
                        dealIds:
                        - v.deal.497fb529e6805351b5dc8057c74a4a52
                        leadIds:
                        - v.lead.d08f345ace24509e911a0ea8e3d2203c
                        noteIds:
                        - v.note.006b4db16b6b50c981a174b02753c390
                        taskIds:
                        - v.task.2322707bbc41577d9806400e2daa25de
                        eventIds:
                        - v.event.0000d2e83d6c5d52a61f2fb860666477
                        eventAttendeeIds:
                        - v.attendee.f63c1bd7215f5150b332d31d9509752f
                        emailIds:
                        - v.email.3ab3a9562af957228c1019127e3c81e1
                        callIds:
                        - v.call.1222707bbc415ee4806400e2daa25ffa
                      additional: {}
      operationId: get-batch-crm-contact
      parameters:
      - schema:
          type: string
        in: query
        name: accessToken
        required: true
        description: The token for the customer's CRM account. This was generated when they connected their account.
      - schema:
          type: string
        in: query
        name: ids
        description: Comma separated list of Contact Id's.
      - schema:
          type: boolean
        in: query
        name: allFields
        description: Returns all fields including non-unifiable and custom fields under the "additional" property in the response
      description: Retrieve Contacts by a set of Id's
components:
  schemas:
    DateFilter:
      type: object
      properties:
        equals:
          type: string
        gt:
          type: string
        lt:
          type: string
        lte:
          type: string
        gte:
          type: string
        not:
          type: string
        in:
          type: array
          items:
            type: string
        notIn:
          type: array
          items:
            type: string
    Contact:
      title: Contact
      type: object
      examples:
      - id: v.contact.e5f32d4fd2115220bd20a2ccf81210ec
        nativeId: '23'
        email: tom@bluecross.com
        firstName: Tom
        lastName: Smith
        jobTitle: Director of Operations
        phone: '2101128833'
        mobilePhone: '2106541111'
        createdTime: '2019-08-24T14:15:22Z'
        modifiedTime: '2019-08-24T14:15:22Z'
        associations:
          accountIds:
          - v.account.0dcb45e051315a6ea63b0f16e73689d9
          dealIds:
          - v.deal.497fb529e6805351b5dc8057c74a4a52
          leadIds:
          - v.lead.d08f345ace24509e911a0ea8e3d2203c
          noteIds:
          - v.note.006b4db16b6b50c981a174b02753c390
          taskIds:
          - v.task.2322707bbc41577d9806400e2daa25de
          eventIds:
          - v.event.0000d2e83d6c5d52a61f2fb860666477
          eventAttendeeIds:
          - v.attendee.f63c1bd7215f5150b332d31d9509752f
          emailIds:
          - v.email.3ab3a9562af957228c1019127e3c81e1
          callIds:
          - v.call.1222707bbc415ee4806400e2daa25ffa
          ownerUserId: v.user.56f653659ea9524b9e0fb0ba67e6f8a0
        additional: {}
      description: Information about an individual affiliated with another CRM Object (e.g., a Lead, a Deal, etc)
      properties:
        id:
          type: string
          description: Unique Vessel Id.
        nativeId:
          type: string
          description: Id of the object in the connected CRM.
        email:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        jobTitle:
          type: string
          description: Not supported by Pipedrive
        phone:
          type: string
          description: The primary phone number for this contact
        mobilePhone:
          type: string
          description: The primary mobile phone number for this contact. Possibly the same as the phone number.
        createdTime:
          type: string
          description: The timestamp that the contact was created
        modifiedTime:
          type: string
          description: The timestamp the contact was last modified
        associations:
          type: object
          required:
          - accountIds
          - dealIds
          - leadIds
          - noteIds
          - taskIds
          - eventIds
          - eventAttendeeIds
          - emailIds
          - callIds
          - ownerUserId
          properties:
            accountIds:
              type: array
              items:
                type: string
            dealIds:
              type: array
              items:
                type: string
            leadIds:
              type: array
              items:
                type: string
            noteIds:
              type: array
              items:
                type: string
            taskIds:
              type: array
              items:
                type: string
            eventIds:
              type: array
              items:
                type: string
            eventAttendeeIds:
              type: array
              items:
                type: string
            emailIds:
              type: array
              items:
                type: string
            callIds:
              type: array
              items:
                type: string
            ownerUserId:
              type: string
        additional:
          type: object
          description: Returned when `allFields` is set in the query params. Includes all data, untransformed, we received from the downstream CRM
      required:
      - id
      - nativeId
      - createdTime
      - modifiedTime
      - associations
    InvalidIds:
      type: array
      items:
        type: string
      description: Ids that didn't return anything. Will be an empty array if all Ids are valid.
    ContactUpdate:
      title: ContactUpdate
      type: object
      examples:
      - email: tom@bluecross.com
        firstName: Tom
        lastName: Smith
        jobTitle: Director of Operations
        phone: '2101128833'
        mobilePhone: '2106541111'
      description: Update a Contact.
      properties:
        email:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        jobTitle:
          type: string
          description: Not supported by Pipedrive
        phone:
          type: string
          description: The primary phone
        mobilePhone:
          type: string
        ownerUserId:
          type: string
          description: The Id of the User to assign this Contact to
        additional:
          type: object
          description: Create any property in the downstream CRM, such as a custom or native property. For a list of all properties see /details.
    Field:
      title: Field
      type: object
      description: '(Alias: property) A field is a key-value pair on a CRM Object that provides information about that object.'
      properties:
        key:
          type: string
          description: 'The key in the CRM object (ex: annualRevenue, numberOfEmployees, etc)'
        name:
          type: string
          description: 'The display name of this field (ex: number of employees, annual revenue, etc)'
        type:
          type: string
          enum:
          - string
          - number
          - datetime
          - date
          - boolean
          - reference
          - phone
          - url
          - id
          - email
          - percent
          - singleselect
          - multiselect
          - address
          - decimal
          - time
          - daterange
          - object
        options:
          type: array
          description: Possible options for this field
          items:
            type: object
            properties:
              key:
                oneOf:
                - type: string
                - type: number
              name:
                type: string
        isArray:
          type: boolean
          description: If this field is an array
        custom:
          type: boolean
          description: If this field is a custom field
        universal:
          type: boolean
          description: If this is a field we've unified across CRMs
        required:
          type: boolean
          description: If this field is required when creating the object
        creatable:
          type: boolean
          description: If this field can be used when creating the object
        updatable:
          type: boolean
          description: If this field can be updated
      required:
      - key
      - name
      - type
      - custom
      - universal
      - required
      - creatable
      - updatable
      examples:
      - key: numberOfEmployees
        name: number of employees
        type: number
        options: null
        isArray: false
        custom: false
        universal: true
        required: false
        creatable: true
        updatable: true
    StringFilter:
      type: object
      properties:
        equals:
          type: string
        contains:
          type: string
        startsWith:
          type: string
        endsWith:
          type: string
        not:
          type: string
        in:
          type: array
          items:
            type: string
        notIn:
          type: array
          items:
            type: string
        mode:
          type: string
          enum:
          - insensitive
    ContactCreate:
      title: ContactCreate
      type: object
      examples:
      - email: tom@bluecross.com
        firstName: Tom
        lastName: Smith
        jobTitle: Director of Operations
        phone: '2101128833'
        mobilePhone: '2106541111'
      description: Properties that a contact can be created with
      properties:
        email:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        jobTitle:
          type: string
          description: Not supported by Pipedrive
        phone:
          type: string
          description: The primary phone
        mobilePhone:
          type: string
        accountId:
          type: string
          description: The Id of the account to associate this contact with
        ownerUserId:
          type: string
          description: The Id of the User to assign this Contact to
        additional:
          type: object
          description: Create any property in the downstream CRM, such as a custom or native property. For a list of all properties see /details.
      required:
      - lastName
  parameters:
    cursor:
      name: cursor
      in: query
      description: The cursor to use for pagination
      schema:
        type: string
    accessToken:
      name: accessToken
      in: query
      description: The token for the customer's account. This was generated when they connected their account.
      required: true
      schema:
        type: string
    allFields:
      name: allFields
      in: query
      description: Returns all fields including non-unifiable and custom fields under the "additional" property in the response
      schema:
        type: boolean
    limit:
      name: limit
      in: query
      description: The number of records to return per page.
      schema:
        type: number
  securitySchemes:
    VesselAPIToken:
      name: vessel-api-token
      type: apiKey
      in: header
