openapi: 3.2.0
info:
  title: CRM API Reference Deals API
  version: '2.0'
  summary: API
servers:
- url: https://api.vessel.dev
security:
- VesselAPIToken: []
tags:
- name: deals
paths:
  /crm/deals:
    parameters: []
    get:
      summary: Get All Deals
      tags:
      - deals
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                title: responseBody
                type: object
                properties:
                  deals:
                    type: array
                    items:
                      $ref: '#/components/schemas/Deal'
                  nextPageCursor:
                    type: string
              examples:
                example-1:
                  value:
                    deals:
                    - id: v.deal.497fb529e6805351b5dc8057c74a4a52
                      nativeId: '84'
                      name: Blue Cross Deal
                      stage: demo
                      amount: 10000
                      closeDate: '2020-08-23T00:00:00Z'
                      probability: '0.4'
                      expectedRevenue: 4000
                      isWon: false
                      isClosed: false
                      modifiedTime: '2019-08-24T14:15:22Z'
                      createdTime: '2019-08-24T14:15:22Z'
                      associations:
                        contactIds:
                        - v.contact.e5f32d4fd2115220bd20a2ccf81210ec
                        accountIds:
                        - v.account.0dcb45e051315a6ea63b0f16e73689d9
                        noteIds:
                        - v.note.006b4db16b6b50c981a174b02753c390
                        taskIds:
                        - v.task.2322707bbc41577d9806400e2daa25de
                        eventIds:
                        - v.event.0000d2e83d6c5d52a61f2fb860666477
                        emailIds:
                        - v.email.3ab3a9562af957228c1019127e3c81e1
                        callIds:
                        - v.call.1222707bbc415ee4806400e2daa25ffa
                        ownerUserId: v.user.56f653659ea9524b9e0fb0ba67e6f8a0
                      additional: {}
                    nextPageCursor: string
      operationId: get-all-crm-deals
      parameters:
      - schema:
          type: string
        in: query
        name: accessToken
        description: The token for the customer's CRM account. This was generated when they connected their account.
        required: true
      - schema:
          type: string
        in: query
        name: cursor
      - schema:
          type: number
        in: query
        name: limit
        description: The number of records to return per page.
      - schema:
          type: boolean
        in: query
        name: allFields
        description: Returns all fields including non-unifiable and custom fields under the "additional" property in the response
      description: Retrieve all Deals
  /crm/deals/search:
    post:
      summary: Search Deals
      tags:
      - deals
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                filters:
                  type: object
                  properties:
                    id:
                      $ref: '#/components/schemas/StringFilter'
                    nativeId:
                      $ref: '#/components/schemas/StringFilter'
                    closeDate:
                      $ref: '#/components/schemas/DateFilter'
                    name:
                      $ref: '#/components/schemas/StringFilter'
                    amount:
                      $ref: '#/components/schemas/NumberFilter'
                    probability:
                      $ref: '#/components/schemas/NumberFilter'
                    stage:
                      $ref: '#/components/schemas/StringFilter'
                    isWon:
                      $ref: '#/components/schemas/BooleanFilter'
                    isClosed:
                      $ref: '#/components/schemas/BooleanFilter'
                    expectedRevenue:
                      $ref: '#/components/schemas/NumberFilter'
                    createdTime:
                      $ref: '#/components/schemas/DateFilter'
                    modifiedTime:
                      $ref: '#/components/schemas/DateFilter'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  deals:
                    type: array
                    items:
                      $ref: '#/components/schemas/Deal'
                  nextPageCursor:
                    type: string
                title: responseBody
              examples:
                example-1:
                  value:
                    deals:
                    - id: v.deal.497fb529e6805351b5dc8057c74a4a52
                      nativeId: '84'
                      name: Blue Cross Deal
                      stage: demo
                      amount: 10000
                      closeDate: '2020-08-23T00:00:00Z'
                      probability: '0.4'
                      expectedRevenue: 4000
                      isWon: false
                      isClosed: false
                      modifiedTime: '2019-08-24T14:15:22Z'
                      createdTime: '2019-08-24T14:15:22Z'
                      associations:
                        contactIds:
                        - v.contact.e5f32d4fd2115220bd20a2ccf81210ec
                        accountIds:
                        - v.account.0dcb45e051315a6ea63b0f16e73689d9
                        noteIds:
                        - v.note.006b4db16b6b50c981a174b02753c390
                        taskIds:
                        - v.task.2322707bbc41577d9806400e2daa25de
                        eventIds:
                        - v.event.0000d2e83d6c5d52a61f2fb860666477
                        emailIds:
                        - v.email.3ab3a9562af957228c1019127e3c81e1
                        callIds:
                        - v.call.1222707bbc415ee4806400e2daa25ffa
                        ownerUserId: v.user.56f653659ea9524b9e0fb0ba67e6f8a0
                      additional: {}
                    nextPageCursor: string
      operationId: search-crm-deals
      description: Search all Deals using filters
      parameters:
      - $ref: '#/components/parameters/accessToken'
      - $ref: '#/components/parameters/cursor'
      - $ref: '#/components/parameters/limit'
      - $ref: '#/components/parameters/allFields'
  /crm/deal:
    parameters: []
    get:
      summary: Get Deal
      tags:
      - deals
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                title: responseBody
                type: object
                properties:
                  deal:
                    $ref: '#/components/schemas/Deal'
              examples:
                example-1:
                  value:
                    deal:
                      id: v.deal.497fb529e6805351b5dc8057c74a4a52
                      nativeId: '84'
                      name: Blue Cross Deal
                      stage: demo
                      amount: 10000
                      closeDate: '2020-08-23T00:00:00Z'
                      probability: '0.4'
                      expectedRevenue: 4000
                      isWon: false
                      isClosed: false
                      modifiedTime: '2019-08-24T14:15:22Z'
                      createdTime: '2019-08-24T14:15:22Z'
                      associations:
                        contactIds:
                        - v.contact.e5f32d4fd2115220bd20a2ccf81210ec
                        accountIds:
                        - v.account.0dcb45e051315a6ea63b0f16e73689d9
                        noteIds:
                        - v.note.006b4db16b6b50c981a174b02753c390
                        taskIds:
                        - v.task.2322707bbc41577d9806400e2daa25de
                        eventIds:
                        - v.event.0000d2e83d6c5d52a61f2fb860666477
                        emailIds:
                        - v.email.3ab3a9562af957228c1019127e3c81e1
                        callIds:
                        - v.call.1222707bbc415ee4806400e2daa25ffa
                        ownerUserId: v.user.56f653659ea9524b9e0fb0ba67e6f8a0
                      additional: {}
      operationId: get-one-crm-deal
      parameters:
      - schema:
          type: string
        in: query
        name: accessToken
        description: The token for the customer's CRM account. This was generated when they connected their account.
        required: true
      - schema:
          type: string
        in: query
        name: id
        required: true
      - schema:
          type: boolean
        in: query
        name: allFields
        description: Returns all fields including non-unifiable and custom fields under the "additional" property in the response
      description: Retrieve a single Deal by Id
    post:
      summary: Create Deal
      tags:
      - deals
      operationId: post-crm-deal
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                title: responseBody
                description: ''
                type: object
                x-examples:
                  example-1:
                    id: '0'
                properties:
                  id:
                    type: string
                required:
                - id
              examples:
                example-1:
                  value:
                    id: '0'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                accessToken:
                  type: string
                deal:
                  $ref: '#/components/schemas/DealCreate'
              required:
              - accessToken
              - deal
            examples:
              example-1:
                value:
                  accessToken: string
                  deal:
                    name: Blue Cross Deal
                    amount: 10000
                    closeDate: '2020-08-23T00:00:00Z'
                    probability: '0.4'
                    stage: closedwon
                    accountId: v.account.0dcb45e051315a6ea63b0f16e73689d9
                    contactId: v.contact.1dcb443051315a6e463b0f16e73689d9
      description: Create a new Deal
    patch:
      summary: Update Deal
      tags:
      - deals
      operationId: put-crm-deal
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                title: responseBody
                description: ''
                type: object
                x-examples:
                  example-1:
                    id: '0'
                properties:
                  id:
                    type: string
                required:
                - id
              examples:
                example-1:
                  value:
                    id: '0'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                accessToken:
                  type: string
                id:
                  type: string
                deal:
                  $ref: '#/components/schemas/DealUpdate'
              required:
              - accessToken
              - id
              - deal
            examples:
              example-1:
                value:
                  accessToken: string
                  id: string
                  deal:
                    name: Blue Cross Deal
                    amount: 10000
                    closeDate: '2020-08-23T00:00:00Z'
                    probability: '0.4'
                    accountId: v.account.0dcb45e051315a6ea63b0f16e73689d9
        description: ''
      description: Update an existing Deal
  /crm/deal/details:
    get:
      summary: Get Deal Details
      tags:
      - deals
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                title: responseBody
                type: object
                properties:
                  fields:
                    type: array
                    items:
                      $ref: '#/components/schemas/Field'
                  nextPageCursor:
                    type: string
              examples:
                example-1:
                  value:
                    fields:
                    - key: amount
                      name: Amount
                      type: number
                      options: null
                      isArray: false
                      custom: false
                      universal: true
                      required: false
                      creatable: true
                      updatable: true
                    nextPageCursor: string
      operationId: get-details-crm-deal
      description: 'Get details about all deals or a particular deal.

        Details include the type, possible values, and other meta data about the fields.'
      parameters:
      - schema:
          type: string
        in: query
        name: accessToken
        description: The token for the customer's CRM account. This was generated when they connected their account.
        required: true
      - schema:
          type: string
        in: query
        name: id
        description: If provided, get the details about a particular deal. If not provided, get details about all deals.
      - schema:
          type: string
        in: query
        name: cursor
      - schema:
          type: boolean
        in: query
        name: allFields
        description: Returns details about native fields.
  /crm/deal/batch:
    parameters: []
    get:
      summary: Get Batch Deals
      tags:
      - deals
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                title: responseBody
                type: object
                properties:
                  deals:
                    type: array
                    items:
                      $ref: '#/components/schemas/Deal'
                  invalidIds:
                    $ref: '#/components/schemas/InvalidIds'
              examples:
                example-1:
                  value:
                    deals:
                    - id: v.deal.497fb529e6805351b5dc8057c74a4a52
                      nativeId: '84'
                      name: Blue Cross Deal
                      stage: demo
                      amount: 10000
                      closeDate: '2020-08-23T00:00:00Z'
                      probability: '0.4'
                      expectedRevenue: 4000
                      isWon: false
                      isClosed: false
                      modifiedTime: '2019-08-24T14:15:22Z'
                      createdTime: '2019-08-24T14:15:22Z'
                      associations:
                        contactIds:
                        - v.contact.e5f32d4fd2115220bd20a2ccf81210ec
                        accountIds:
                        - v.account.0dcb45e051315a6ea63b0f16e73689d9
                        noteIds:
                        - v.note.006b4db16b6b50c981a174b02753c390
                        taskIds:
                        - v.task.2322707bbc41577d9806400e2daa25de
                        eventIds:
                        - v.event.0000d2e83d6c5d52a61f2fb860666477
                        emailIds:
                        - v.email.3ab3a9562af957228c1019127e3c81e1
                        callIds:
                        - v.call.1222707bbc415ee4806400e2daa25ffa
                        ownerUserId: v.user.56f653659ea9524b9e0fb0ba67e6f8a0
                      additional: {}
      operationId: get-batch-crm-deal
      parameters:
      - schema:
          type: string
        in: query
        name: accessToken
        required: true
        description: The token for the customer's CRM account. This was generated when they connected their account.
      - schema:
          type: string
        in: query
        name: ids
        description: Comma separated list of Deal Id's.
      - schema:
          type: boolean
        in: query
        name: allFields
        description: Returns all fields including non-unifiable and custom fields under the "additional" property in the response
      description: Retrieve Deals by a set of Id's
components:
  schemas:
    DateFilter:
      type: object
      properties:
        equals:
          type: string
        gt:
          type: string
        lt:
          type: string
        lte:
          type: string
        gte:
          type: string
        not:
          type: string
        in:
          type: array
          items:
            type: string
        notIn:
          type: array
          items:
            type: string
    Deal:
      title: Deal
      type: object
      examples:
      - id: v.deal.497fb529e6805351b5dc8057c74a4a52
        nativeId: '84'
        name: Blue Cross Deal
        stage: demo
        amount: 10000
        closeDate: '2020-08-23T00:00:00Z'
        probability: '0.4'
        expectedRevenue: 4000
        isWon: false
        isClosed: false
        modifiedTime: '2019-08-24T14:15:22Z'
        createdTime: '2019-08-24T14:15:22Z'
        associations:
          contactIds:
          - v.contact.e5f32d4fd2115220bd20a2ccf81210ec
          accountIds:
          - v.account.0dcb45e051315a6ea63b0f16e73689d9
          noteIds:
          - v.note.006b4db16b6b50c981a174b02753c390
          taskIds:
          - v.task.2322707bbc41577d9806400e2daa25de
          eventIds:
          - v.event.0000d2e83d6c5d52a61f2fb860666477
          emailIds:
          - v.email.3ab3a9562af957228c1019127e3c81e1
          callIds:
          - v.call.1222707bbc415ee4806400e2daa25ffa
          ownerUserId: v.user.56f653659ea9524b9e0fb0ba67e6f8a0
        additional: {}
      description: '(Alias: Opportunity) An object representing either the opportunity to sell a product to an Account, or in the case of an `isWon` deal, a product sold to an Account.

        *CRM Caveats*:

        - Pipedrive: Users must have "Deal probability" turned on for the given pipeline for probability to be configurable and returned.'
      properties:
        id:
          type: string
          description: Unique Vessel Id.
        nativeId:
          type: string
          description: Id of the object in the connected CRM.
        name:
          type: string
          description: Optional name for this deal
        stage:
          type: string
          description: The stage of the pipeline the deal is in. See /deal/details for possible values
        amount:
          type: number
          description: Total deal money value
        closeDate:
          type: string
          description: When this deal is projected to be closed
        probability:
          type: string
          description: Decimal probability of closing this deal.
        expectedRevenue:
          type: number
          description: probability * amount. This is a computed property
        isWon:
          type: boolean
          description: If this deal has been won. This is a computed property based on stage
        isClosed:
          type: boolean
          description: If this deal is closed (either closed-won or closed-lost). This is a computed property based on stage
        createdTime:
          type: string
          description: The timestamp that the deal was created
        modifiedTime:
          type: string
          description: The timestamp the deal was last modified
        associations:
          type: object
          required:
          - contactIds
          - accountIds
          - noteIds
          - taskIds
          - emailIds
          - callIds
          - ownerUserId
          properties:
            contactIds:
              type: array
              items:
                type: string
            accountIds:
              type: array
              items:
                type: string
            noteIds:
              type: array
              items:
                type: string
            taskIds:
              type: array
              items:
                type: string
            eventIds:
              type: array
              items:
                type: string
            emailIds:
              type: array
              items:
                type: string
            callIds:
              type: array
              items:
                type: string
            ownerUserId:
              type: string
              description: The Id of the User that owns this Deal
        additional:
          type: object
          description: Returned when `allFields` is set in the query params. Includes all data, untransformed, we received from the downstream CRM
      required:
      - id
      - nativeId
      - name
      - closeDate
      - createdTime
      - modifiedTime
      - associations
    InvalidIds:
      type: array
      items:
        type: string
      description: Ids that didn't return anything. Will be an empty array if all Ids are valid.
    BooleanFilter:
      type: object
      properties:
        equals:
          type: boolean
        not:
          type: boolean
    Field:
      title: Field
      type: object
      description: '(Alias: property) A field is a key-value pair on a CRM Object that provides information about that object.'
      properties:
        key:
          type: string
          description: 'The key in the CRM object (ex: annualRevenue, numberOfEmployees, etc)'
        name:
          type: string
          description: 'The display name of this field (ex: number of employees, annual revenue, etc)'
        type:
          type: string
          enum:
          - string
          - number
          - datetime
          - date
          - boolean
          - reference
          - phone
          - url
          - id
          - email
          - percent
          - singleselect
          - multiselect
          - address
          - decimal
          - time
          - daterange
          - object
        options:
          type: array
          description: Possible options for this field
          items:
            type: object
            properties:
              key:
                oneOf:
                - type: string
                - type: number
              name:
                type: string
        isArray:
          type: boolean
          description: If this field is an array
        custom:
          type: boolean
          description: If this field is a custom field
        universal:
          type: boolean
          description: If this is a field we've unified across CRMs
        required:
          type: boolean
          description: If this field is required when creating the object
        creatable:
          type: boolean
          description: If this field can be used when creating the object
        updatable:
          type: boolean
          description: If this field can be updated
      required:
      - key
      - name
      - type
      - custom
      - universal
      - required
      - creatable
      - updatable
      examples:
      - key: numberOfEmployees
        name: number of employees
        type: number
        options: null
        isArray: false
        custom: false
        universal: true
        required: false
        creatable: true
        updatable: true
    NumberFilter:
      type: object
      properties:
        equals:
          type: number
        gt:
          type: number
        lt:
          type: number
        lte:
          type: number
        gte:
          type: number
        not:
          type: number
        in:
          type: array
          items:
            type: number
        notIn:
          type: array
          items:
            type: number
    DealUpdate:
      title: DealUpdate
      type: object
      examples:
      - name: Blue Cross Deal
        amount: 10000
        closeDate: '2020-08-23T00:00:00Z'
        probability: '0.4'
      properties:
        name:
          type: string
        amount:
          type: number
        closeDate:
          type: string
        probability:
          type: string
          description: Decimal probability of closing the deal
        stage:
          type: string
          description: The stage the deal is in. See /deal/details for possible values
        accountId:
          type: string
          description: Update the account this deal is associated with.
        additional:
          type: object
          description: Create any property in the downstream CRM, such as a custom or native property. For a list of all properties see /details.
      required:
      - closeDate
    DealCreate:
      title: DealCreate
      type: object
      properties:
        name:
          type: string
        amount:
          type: number
        closeDate:
          type: string
        probability:
          type: string
          description: Decimal probability of closing the deal
        stage:
          type: string
          description: The stage the deal is in. See /deal/details for possible value
        accountId:
          type: string
          description: The Id of the account to associate this deal with
        contactId:
          type: string
          description: Only supported for Salesforce and HubSpot. The Id of the contact to associate this deal with
        additional:
          type: object
          description: Create any property in the downstream CRM, such as a custom or native property. For a list of all properties see /details.
      required:
      - name
      - closeDate
    StringFilter:
      type: object
      properties:
        equals:
          type: string
        contains:
          type: string
        startsWith:
          type: string
        endsWith:
          type: string
        not:
          type: string
        in:
          type: array
          items:
            type: string
        notIn:
          type: array
          items:
            type: string
        mode:
          type: string
          enum:
          - insensitive
  parameters:
    cursor:
      name: cursor
      in: query
      description: The cursor to use for pagination
      schema:
        type: string
    accessToken:
      name: accessToken
      in: query
      description: The token for the customer's account. This was generated when they connected their account.
      required: true
      schema:
        type: string
    allFields:
      name: allFields
      in: query
      description: Returns all fields including non-unifiable and custom fields under the "additional" property in the response
      schema:
        type: boolean
    limit:
      name: limit
      in: query
      description: The number of records to return per page.
      schema:
        type: number
  securitySchemes:
    VesselAPIToken:
      name: vessel-api-token
      type: apiKey
      in: header
